### ISSUE TITLE
感谢作者的无私分享，不过获取旬空是不是有点问题

### ISSUE THREAD

**Issue by Bameirilyo** [6tail/tyme4go#1]
不知道是不是我使用的方法有误，发生了panic

<img width="910" alt="企业微信截图_e7e8abf6-1156-43df-8ec1-7c5d96c7005f" src="https://github.com/user-attachments/assets/c3580a4d-a0d0-455b-a27f-a09b6aa6bc6c">

<img width="528" alt="企业微信截图_6b642bd3-1e86-4a71-8398-cccc6667f367" src="https://github.com/user-attachments/assets/6a6ed453-28f8-469a-a3db-e4c75e81b3ff">

感觉还有一点点小问题：
GetLunarHour()稍微命名有点歧义，一开始以为是获取的“小时”数，而不是整个时间；
GetSixtyCycle()也是命名有点歧义，只返回了时的干支，会以为是整个的干支；

**Comment by 6tail** [comment]
1、旬空问题待我检查一下。
2、可能你理解上有些偏差，所有的方法或属性，仅仅是该对象特有的。
SolarTime为精确到秒的公历时刻，solarTime.GetLunarHour()是指公历时刻转换为农历时辰。LunarHour为农历时辰，获取干支，自然是时辰的干支。时辰提供了获取日干支、月干支、年干支的方法，也提供了获取农历日、农历月、农历年的方法。同理，农历日也能获取日干支，月干支、年干支，农历日也能获取农历月、农历年。

**Comment by 6tail** [comment]
v1.0.3 已修复数组下标越界的问题。

**Comment by Bameirilyo** [comment]
这修复速度，无敌了 :+1:
其他几个确实是我理解有误，只想着阳历、农历、干支的转换了
